name: gencore_de_novo_genomic_soapdenovo2
version: 1.1
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- soapdenovo2-gapcloser=1.12
- soapdenovo2-prepare=2.0
- soapdenovo2=2.40
