name: gencore_de_novo_transcriptome_1.0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-slurm=2.58
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- blat=35
- picard=2.5.0
- prinseq=0.20.4
- augustus=3.2.2
- blast=2.2.31
- bwa=0.7.15
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- vcflib=1.0.0_rc1
- bamtools=2.4.0
- trimmomatic=0.36
- hmmer=3.1b2
- rsem=1.2.28
- salmon=0.6.0
- star=2.5.2a
- sickle=0.5
- quast=4.1
- seqtk=1.2
- pear=0.9.6
- bowtie2=2.2.8
- circos=0.69.2
- tophat=2.1.0
- cufflinks=2.2.1
- bioconductor-deseq=1.22.1
- bioconductor-deseq2=1.10.1
- bioconductor-edger=3.14.0
- htseq=0.6.1.post1
- gencore_de_novo_transcriptome_docs=1.0
