name: gencore_rnaseq_quant
version: 1.0
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - stringtie=1.3.0
  - cufflinks
  - htseq=0.6.1.post1
  - samtools=1.3.1
  - bcftools=1.3.1
