name: gencore_rnaseq_quant
version: 2.0
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools=1.3.1
  - cufflinks=2.2.1
  - htseq=0.6.1.post1
  - libdeflate=0.8
  - pysam=0.10.0
  - samtools=1.3.1
  - stringtie=1.3.0
  - bzip2=1.0.6
  - matplotlib=2.2.2
  - numpy=1.14.3

