name: gencore_de_novo_genomic_soapdenovo2
version: 1.0
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- soapdenovo2-gapcloser=1.12
- soapdenovo2-prepare=2.0
- soapdenovo2=2.40
- gencore_de_novo_genomic_soapdenovo2_docs=1.0
