name: gencore_rad
version: 1.1
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- blat=35
- blast=2.2.31
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- freebayes=1.0.2.29
- vcflib=1.0.0_rc1
- bamtools=2.4.0
- rainbow=2.0.4
- seqtk=1.2
- cd-hit=4.6.4
- stacks=1.40
- bowtie2=2.2.8
