name: gencore_variant_detection_1.0
channels:
- bioconda
- r
- jerowe
dependencies:
- perl-hpc-runner-slurm=2.58
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- discovar=52488
- discovardenovo=52488
- blast=2.2.31
- bwa=0.7.15
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- freebayes=1.0.2.29
- bamtools=2.4.0
- seqtk=1.2
- pear=0.9.6
- bowtie2=2.2.8
- tophat=2.1.0
- cufflinks=2.2.1
- circos=0.69.2
- star=2.5.2a
- blat=35
- gatk=3.5
- picard=2.5.0
- prinseq=0.20.4
- snpeff=4.3
- vcflib=1.0.0_rc1
- gencore_variant_detection_docs=1.0
