name: gencore_base_1.0
channels:
- conda-forge
- defaults
- r
- bioconda
- nyuad-cgsb
dependencies:
- perl-app-cpanminus
- perl-hpc-runner-slurm=2.58
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- r-base=3.3.1
- r-essentials=3.3.1
- r-ggplot2
- bioconductor-biocgenerics
- gencore_base_docs=1.0
