name: gencore_base
version: 1.1
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-app-cpanminus
- pip
- setuptools
- r-base=3.3.1
- r-ggplot2
- bioconductor-biocgenerics
