name: gencore_base
version: 1.0
build: 1
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-app-cpanminus
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- r-base=3.3.1
- r-ggplot2
- bioconductor-biocgenerics
- gencore_base_docs=1.0
