version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "A first hello"
      - run: echo pwd
      - run: ls -lah
      - run:
          name: install dependencies
          command: |
            scripts/travis-setup.sh
      - run:
          name: run tests
          command: |
            scripts/travis-run.sh
