version:               2
machine:
  environment:
    CIRCLE_ENV:        test
    CONDA_PKGS_DIRS:   '~/anaconda3/pkgs'
    CONDA_BLD_PATH:    '~/anaconda3/conda-bld'

  cache_directories:
    - "~/anaconda3/pkgs"

jobs:
  build:
    docker:
      - image:         continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - run:           echo "A first hello"
      - run:           echo pwd
      - run:           ls -lah
      - run:
          name:        install dependencies
          command:     |
            scripts/travis-setup.sh
      - run:
          name:        run tests
          command:     |
            scripts/travis-run.sh
            test:
