version:               2

machine:

  environment:
    CIRCLE_ENV:        test
    CONDA_BLD_PATH:    '~/anaconda3/conda-bld'
    ANACONDA_USER: nyuad-cgsb
    GITHUB_USER: nyuad-cgsb
    GITHUB_REPO: nyuad-hpc-module-configs
    CONTAINER_NAMESPACE: 'nyuad_cgsb'
    CONDA_R: '3.4.1'
    CONDA_PERL: '5.22.0'
    CONDA_HTSLIB: "1.6"
    CONDA_BOOST: "1.64"
    CONDA_NPY: "112"
    CONDA_NCURSES: "5.9"
    CONDA_GSL: "1.16"
    CONDA_GMP: "5.1"
    CONDA_HDF5: "1.8.17"
    CONDA_ZLIB: "1.2.8"
    CONDA_BZIP2: "1.0"
    CONDA_XZ: "5.2"
    # MINICONDA_VER: '4.3.21'

jobs:
  build:
    docker:
      - image:         continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - run:           conda info
      - run:
          name:        install dependencies
          command:     |
            scripts/travis-setup.sh
      - run:
          name:        run tests
          command:     |
            scripts/travis-run.sh
            test:
