name: gencore_rnaseq
version: 1.3
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - samtools=1.3.1
  - bcftools=1.3.1
  - kallisto
  - blat=35
  - gatk=3.6
  - picard=2.5.0
  - trimmomatic=0.36
  - fastqc=0.11.5
  - prinseq=0.20.4
  - star=2.5.2a
  - vcftools=0.1.14
  - bedtools=2.25.0
  - vcflib
  - bamtools=2.4.0
  - seqtk=1.2
  - bowtie2=2.2.8
  - tophat=2.1.0
  - cufflinks
  - r-base
  - r-essentials
  - r-cairo
  - bioconductor-deseq2
  - bioconductor-edger=3.14.0
  - bioconductor-cummerbund=2.16.0
  - bioconductor-genomicranges
  - bioconductor-gviz=1.16.5
  - bioconductor-biovizbase=1.18.0
  - bioconductor-s4vectors
  - bioconductor-ballgown=2.2.0
  - htseq=0.6.1.post1
  - hisat2=2.0.4
  - stringtie=1.3.0
