name: gencore_rnaseq_align
version: 1.0
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - tophat=2.1.0
  - kallisto
  - star=2.5.2a
  - bowtie2=2.2.8
  - salmon
  - hisat2=2.0.4
  - samtools=1.3.1
  - bcftools=1.3.1
