name: gencore_variant_detection
version: 2.0
build: 0
channels:
- bioconda
- conda-forge
- defaults
- nyuad-cgsb
dependencies:
- discovar=52488
- discovardenovo=52488
- blast=2.2.31
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- freebayes=1.0.2.29
- bamtools=2.4.0
- seqtk=1.2
- pear=0.9.6
- blat=35
- gatk=3.5
- picard=2.5.0
- prinseq=0.20.4
- snpeff=4.3
- snpsift=4.3
- vcflib=1.0.0_rc1
- r-base=3.3.1
- r-essentials
- bioconductor-biobase=2.32.0
- ensembl-vep=9.5.1
