##This should be from BioSAILs
FROM quay.io/nyuad_cgsb/gencore_biosails

WORKDIR $HOME/.eb/custom_repos/nyuad-hpc-module-configs

ENV PATH=/usr/share/lmod/lmod/libexec:$PATH
RUN git pull origin master

RUN cat $ROBOT/{{name}}-{{version}}.eb

RUN bash -c "source /usr/share/lmod/lmod/init/bash &&  module load  Anaconda3 && \
	pip install git+https://github.com/nyuad-cgsb/gencore_app"

RUN bash -c "source activate $EB_ENV && \
	eb  --robot --robot-paths=$ROBOT  {{ name }}-{{ version }}.eb"

RUN bash -c "source /usr/share/lmod/lmod/init/bash &&  module load {{name}} && conda clean --all"
RUN echo "module load {{name}}" >> ~/.bashrc

COPY bash_entrypoint.sh /home/ebuser/bin/bash_entrypoint.sh
#RUN chmod 777 /home/ebuser/bin/*.sh
#RUN chown -R ebuser:ebuser /home/ebuser/bin

ENTRYPOINT ["/home/ebuser/bin/bash_entrypoint.sh"]
