##This should be from BioSAILs
FROM quay.io/nyuad_cgsb/easybuild

WORKDIR $HOME/.eb/custom_repos/nyuad-hpc-module-configs

RUN git pull origin master

RUN ls -lah $ROBOT
RUN cat $ROBOT/{{name}}-{{version}}.eb

RUN bash -c "conda install -y gosu tini"
RUN bash -c "source activate $EB_ENV && \
	eb  --robot --robot-paths=$ROBOT  {{ name }}-{{ version }}.eb && \
        module avail"

RUN echo "source activate $EB_ENV" >> ~/.bashrc
RUN echo "module load gencore_biosails" >> ~/.bashrc

USER root

RUN apt-get update -y
RUN apt-get install awscli unzip -y
RUN apt-get install -y vim-tiny

COPY fetch_and_run.sh /home/ebuser/fetch_and_run.sh
RUN chown ebuser:ebuser /home/ebuser/fetch_and_run.sh
RUN chmod 777 /home/ebuser/fetch_and_run.sh

USER ebuser

WORKDIR /home/ebuser
CMD ["source activate $EB_ENV"]
CMD ["module avail"]

ENTRYPOINT ["gosu exec $@"]
