name: gencore_qc
version: 1.1
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- trimmomatic=0.36
- fastqc=0.11.5
- fastx_toolkit=0.0.14
- pyfasta=0.5.2
- pyfaidx=0.4.7.1
- pyfastaq=3.11.0
- python=3.5
- multiqc=0.8
- deeptools=2.3.2
- qualimap=2.2.2a
