name: gencore_rnaseq_align
version: 2.0
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools=1.3.1
  - bowtie2=2.2.8
  - hisat2=2.0.4
  - kallisto=0.44.0
  - perl
  - salmon=0.10.2
  - samtools=1.3.1
  - star=2.5.2a
  - tophat=2.1.0
  - boost=1.64.0
  - boost-cpp=1.64.0
  - bzip2=1.0.6

