name: gencore_qiime_1.0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-slurm=2.58
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- qiime=1.9.1
- gencore_qiime_docs=1.0
