name: gencore_aligners
version: 2.0
build: 0
channels:
  - nyuad-cgsb
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bwa=0.7.4
  - bcftools=1.3.1
  - bowtie2=2.2.8
  - hisat2=2.0.4
  - kallisto=0.44.0
  - salmon=0.10.2
  - samtools=1.3.1
  - star=2.5.2a
  - tophat=2.1.0
